spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
            trust: "*"
        starttls:
          enable: true
    protocol: smtp

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  banner:
    location: banner
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: School-Management-System-Spring
    security:
      jwt:
        secret: ${JWT_SECRET}
        expiration: 3600000 # 1 hour
        refresh-token-expiration: 86400000 # 1 day

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    filter: true
    operations-sorter: method
  show-actuator: true
  disable-i18n: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/admin/management-server
  endpoint:
    health:
      show-details: always

app:
  user:
    email: ${ADMIN_EMAIL} # admin account
    password: ${ADMIN_PASSWORD}
    firstName: Francisco
    lastName: Freitas

logging:
  include-application-name: true
  file:
    path: ./logs
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

email:
  from: ${MAIL_USERNAME}
  subject: Account Confirmation
  confirmation:
    frontend-url: http://localhost:4200/confirm-account
  code:
    length: 6
    expiration: 15 # 15 minutes

storage:
  profile-directory: "/application/storage/profiles"
  book-covers-directory: "/application/storage/book-covers"