spring:
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  banner:
    location: banner
  datasource:
    url: jdbc:postgresql://localhost:5432/school_management_database?useSSL=false&serverTimezone=Europe/Lisbon
    username: ffreitas
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  application:
    name: School-Management-System-Spring
    security:
      jwt:
        secret: 1ziBfO3ls0+XFugZPnPLiLbTWoGDxB8e3W1kKISsJZPfIvstCGVqJEV67f0hqWGtjqvIwuQAEQD23/Pzt5p0/A==
        expiration: 300000 # 5 minutes
        refresh-token-expiration: 3600000 # 1 hour
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    filter: true
    operations-sorter: method
  show-actuator: true
  disable-i18n: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/admin/management-server
  endpoint:
    health:
      show-details: always
app:
  user:
    email: francisco.freitas.ff@gmail.com #admin account
    password: password123456
    firstName: Francisco
    lastName: Freitas
logging:
  include-application-name: true
  file:
    path: ./logs
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

email:
  from: francisco.freitas.ff@gmail.com
  subject: Account Confirmation
  confirmation:
    frontend-url: http://localhost:4200/confirm-account
  code:
    length: 6
    expiration: 10 # 10 minutes

storage:
  profile-directory: "/application/storage/profiles"
  book-covers-directory: "/application/storage/book-covers"

cors:
  origins: http://localhost:4200,http://localhost:8080